# frozen_string_literal: true

module MLC
  module Backends
    module Cpp
      # Main coordinator for C++ code generation
      # Entry point for the new backend architecture
      class Orchestrator
        attr_reader :container, :context

        def initialize(type_registry:, function_registry:)
          @container = Container.new(
            type_registry: type_registry,
            function_registry: function_registry
          )
          @context = Context.new(@container)
          # Initialize RuleEngine after Context is created
          @container.rule_engine = Services::RuleEngine.new(@context)
        end

        # Main entry point: SemanticIR → C++ source code
        def generate_cpp(semantic_ir)
          header = generate_header
          includes = generate_includes
          forward_decls = generate_forward_declarations(semantic_ir)
          type_defs = generate_type_definitions(semantic_ir)
          functions = generate_functions(semantic_ir)

          [header, includes, forward_decls, type_defs, functions].join("\n\n")
        end

        private

        def generate_header
          "// Generated by MLC Backends::Cpp v#{VERSION}\n" \
          "// DO NOT EDIT: This file is auto-generated"
        end

        def generate_includes
          <<~CPP.chomp
            #include <iostream>
            #include <string>
            #include <vector>
            #include <functional>
            #include <memory>
            #include <cstdint>
            #include "mlc/runtime.hpp"
          CPP
        end

        def generate_forward_declarations(semantic_ir)
          # TODO: Extract type declarations from SemanticIR
          "// Forward declarations"
        end

        def generate_type_definitions(semantic_ir)
          # TODO: Generate struct/class definitions
          "// Type definitions"
        end

        def generate_functions(semantic_ir)
          # TODO: Generate function implementations
          "// Function definitions"
        end
      end
    end
  end
end
