AllCops:
  NewCops: disable
  TargetRubyVersion: 4.0
  Exclude:
    - 'docs/**/*'
    - 'runtime/**/*'
    - 'bin/**/*'
    - 'test/fixtures/**/*'
    - 'misc/**/*'
Layout/LineLength:
  Max: 140
Style/FrozenStringLiteralComment:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/UselessAssignment:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/EmptyWhen:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/MultipleComparison:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: true
Lint/RedundantCopEnableDirective:
  Enabled: true
Lint/SafeNavigationChain:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
